---
# tasks file for remove_vpc_peering
- name: set ec2_vpc_name
  set_fact: ec2_vpc_name="{{ ec2_name_prefix }}-vpc"

- name: Get the VPC ID for "{{ ec2_vpc_name }}"
  ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ ec2_vpc_name }}"
    region: "{{ ec2_region }}"
  register: vpc_net_info

- name: set ec2_vpc_id
  set_fact: ec2_vpc_id="{{ (vpc_net_info.vpcs | selectattr('tags.Name','equalto', ec2_vpc_name ) | first).vpc_id }}"

- name: List all vpc peers
  ec2_vpc_peering_info:
    region: "{{ ec2_region }}"
    filters:
      requester-vpc-info.vpc-id: "{{ ec2_vpc_id }}"
  register: vpc_peer

- name: set ec2_vpc_peering_id
  set_fact: ec2_vpc_peering_id="{{ vpc_peer.result[0].vpc_peering_connection_id }}"

# We need the accepter vpc id because we need to delete the route from it's route table.
# We'll delete the requester route table completely, but the accepter is just a route removal.
- name: set accepter_vpc_id
  set_fact: accepter_vpc_id="{{ vpc_peer.result[0].accepter_vpc_info.vpc_id }}"

- name: Get route table info for vpc peer target
  ec2_vpc_route_table_info:
    region: "{{ ec2_region }}"
    filters:
      vpc-id: "{{ accepter_vpc_id }}"
  register: rtb_info

- name: rtb_info
  debug:
    msg: "{{ rtb_info }}"

- name: Get destination route for vpc_peering_connection
  set_fact: 
    accepter_route: "{{ (rtb_info
      | selectattr('vpc_peering_connection_id', 'defined')
      | map(attribute='vpc_peering_connection_id')
      | list
      | unique }}"

#- debug: msg="{{ (rtb_info | selectattr('tags.Name','equalto','mytag1') | first).id }}"

#- name: delete a local VPC peering Connection
#  ec2_vpc_peer:
#    region: "{{ ec2_region }}"
    #peering_id: "{{ vpc_peer.result[0].vpc_peering_connection_id }}"
#    state: absent
#  register: vpc_peer
#
#- name: vpc_peer after deletion
#  debug:
#    msg: "{{ vpc_peer }}"