---
# tasks file for remove_vpc_peering
- name: Get the VPC ID for {{ ec2_name_prefix }}-vpc
  ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ ec2_name_prefix }}-vpc"
    region: "{{ ec2_region }}"
  register: vpc_net_facts

- name: vpc_net_facts
  debug:
    msg: "{{ vpc_net_facts }}"

- name: List all vpc peers
  ec2_vpc_peering_info:
    region: "{{ ec2_region }}"
    filters:
      requester-vpc-info.vpc-id: "{{ vpc_net_facts.vpcs[0].id }}"
  register: vpc_peer

- name: vpc_peer.result from ec2_vpc_peering_info
  debug:
    msg: "{{ vpc_peer.result }}"

- name: Get route table info for vpc peer target
  ec2_vpc_route_table_info:
    region: "{{ ec2_region }}"
  register: rtb_info

- name: rtb_info
  debug:
    msg: "{{ rtb_info }}"

#- name: delete a local VPC peering Connection
#  ec2_vpc_peer:
#    region: "{{ ec2_region }}"
#    peering_id: "{{ vpc_peer.result[0].vpc_peering_connection_id }}"
#    state: absent
#  register: vpc_peer

- name: vpc_peer after deletion
  debug:
    msg: "{{ vpc_peer }}"