---
# tasks file for remove_vpc_peering
- name: List all vpc peers
  ec2_vpc_peering_info:
    region: us-east-1
  register: all_vpc_peers

- name: Debugging the result
  debug:
    msg: "{{ all_vpc_peers.result }}"